framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      # async: '%env(MESSENGER_TRANSPORT_DSN)%'
      # failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'
      amqp_test_rabbit:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: messenger.transport.symfony_serializer
        options:
          vhost: lc_api
          heartbeat: 60
          exchange:
            name: test_rabbit
            type: fanout
          queues:
            test_rabbit: ~

      amqp_test_rabbit_custom:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: App\Serializer\ExternalJsonMessageSerializer
        options:
          vhost: lc_api
          heartbeat: 60
          exchange:
            name: test_rabbit_custom
            type: fanout
          queues:
            test_rabbit_custom: ~

    routing:
      # Route your messages to the transports
      # 'App\Message\YourMessage': async
      App\Message\TestRabbit: amqp_test_rabbit
      App\Message\TestRabbitCustomJson: amqp_test_rabbit_custom
